// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/customer/customer.proto

package go_micro_service_customer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Customer service

func NewCustomerEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Customer service

type CustomerService interface {
	Detail(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Customer_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Customer_PingPongService, error)
}

type customerService struct {
	c    client.Client
	name string
}

func NewCustomerService(name string, c client.Client) CustomerService {
	return &customerService{
		c:    c,
		name: name,
	}
}

func (c *customerService) Detail(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Customer.Detail", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Customer_StreamService, error) {
	req := c.c.NewRequest(c.name, "Customer.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &customerServiceStream{stream}, nil
}

type Customer_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type customerServiceStream struct {
	stream client.Stream
}

func (x *customerServiceStream) Close() error {
	return x.stream.Close()
}

func (x *customerServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *customerServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *customerServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *customerServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *customerService) PingPong(ctx context.Context, opts ...client.CallOption) (Customer_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Customer.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &customerServicePingPong{stream}, nil
}

type Customer_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type customerServicePingPong struct {
	stream client.Stream
}

func (x *customerServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *customerServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *customerServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *customerServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *customerServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *customerServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Customer service

type CustomerHandler interface {
	Detail(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Customer_StreamStream) error
	PingPong(context.Context, Customer_PingPongStream) error
}

func RegisterCustomerHandler(s server.Server, hdlr CustomerHandler, opts ...server.HandlerOption) error {
	type customer interface {
		Detail(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Customer struct {
		customer
	}
	h := &customerHandler{hdlr}
	return s.Handle(s.NewHandler(&Customer{h}, opts...))
}

type customerHandler struct {
	CustomerHandler
}

func (h *customerHandler) Detail(ctx context.Context, in *Request, out *Response) error {
	return h.CustomerHandler.Detail(ctx, in, out)
}

func (h *customerHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CustomerHandler.Stream(ctx, m, &customerStreamStream{stream})
}

type Customer_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type customerStreamStream struct {
	stream server.Stream
}

func (x *customerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *customerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *customerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *customerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *customerStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *customerHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.CustomerHandler.PingPong(ctx, &customerPingPongStream{stream})
}

type Customer_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type customerPingPongStream struct {
	stream server.Stream
}

func (x *customerPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *customerPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *customerPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *customerPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *customerPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *customerPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
